ANCHO_CASILLAS = 16
ALTO_CASILLAS = 8
ALTO_PANEL = 200

TAMANO_CASILLA = 62

ANCHO_PANTALLA = ANCHO_CASILLAS * TAMANO_CASILLA  # 992
ALTO_PANTALLA = ALTO_CASILLAS * TAMANO_CASILLA + ALTO_PANEL  # 696
ALTO_MAPA = ALTO_CASILLAS * TAMANO_CASILLA  # 496