ANCHO_PANTALLA = 1000
ALTO_PANTALLA = 700
ALTO_PANEL = 20
ALTO_MAPA = ALTO_PANTALLA - ALTO_PANEL - 20

ANCHO_CASILLAS = 16
ALTO_CASILLAS = 8
TAMANO_CASILLA = min(
    ANCHO_PANTALLA // ANCHO_CASILLAS,        # limitado por ancho
    (ALTO_PANTALLA - ALTO_PANEL) // ALTO_CASILLAS  # limitado por alto
)